/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_aachen_comsys_androidcv_DescriptorController */

#ifndef _Included_de_rwth_aachen_comsys_androidcv_DescriptorController
#define _Included_de_rwth_aachen_comsys_androidcv_DescriptorController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_rwth_aachen_comsys_androidcv_DescriptorController
 * Method:    nativeLoadDescriptor
 * Signature: ()V
 *
 * Load binary descriptors into a vector
 * Return: void
 */
JNIEXPORT void JNICALL Java_de_rwth_aachen_comsys_androidcv_DescriptorController_nativeLoadDescriptor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_rwth_aachen_comsys_androidcv_DescriptorController
 * Method:    nativeTrainMatcher
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_aachen_comsys_androidcv_DescriptorController_nativeTrainMatcher
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     de_rwth_aachen_comsys_androidcv_DescriptorController
 * Method:    nativeFindMatch
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_aachen_comsys_androidcv_DescriptorController_nativeFindMatch
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_aachen_comsys_androidcv_DescriptorController
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_aachen_comsys_androidcv_DescriptorController_nativeDestroy
  (JNIEnv *);

#ifdef __cplusplus
}
#endif
#endif
